// Auto-generated TypeScript types from database schema
// DO NOT EDIT MANUALLY - This file is generated by generate_database_types tool

export interface SalaryConfigsS6A7Bcadf8Row {
  id: number;
  corp_id: string | null;
  app_id: string | null;
  emp_id: string | null;
  config_type: string;
  config_key: string;
  config_value: number;
  effective_date: string | null;
  is_active: boolean | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type SalaryConfigsS6A7Bcadf8Insert = Omit<SalaryConfigsS6A7Bcadf8Row, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type SalaryConfigsS6A7Bcadf8Update = Partial<SalaryConfigsS6A7Bcadf8Insert>;

export interface SalaryRecordsS6A7Bcadf8Row {
  id: number;
  corp_id: string | null;
  app_id: string | null;
  emp_id: string | null;
  sampler_id: number | null;  // FK -> samplers.id
  year_month: string;
  base_salary: number | null;
  piece_rate_salary: number | null;
  hourly_salary: number | null;
  overtime_pay: number | null;
  performance_bonus: number | null;
  deductions: number | null;
  total_salary: number | null;
  actual_salary: number | null;
  payment_status: string | null;
  payment_date: string | null;
  notes: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type SalaryRecordsS6A7Bcadf8Insert = Omit<SalaryRecordsS6A7Bcadf8Row, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type SalaryRecordsS6A7Bcadf8Update = Partial<SalaryRecordsS6A7Bcadf8Insert>;

export interface SamplersRow {
  id: number;
  corp_id: string | null;
  app_id: string | null;
  emp_id: string | null;
  name: string;
  employee_code: string | null;
  phone: string | null;
  entry_date: string | null;
  status: string | null;
  base_salary: number | null;
  skill_level: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type SamplersInsert = Omit<SamplersRow, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type SamplersUpdate = Partial<SamplersInsert>;

export interface SamplingTasksRow {
  id: number;
  corp_id: string | null;
  app_id: string | null;
  emp_id: string | null;
  task_code: string | null;
  task_type: string;
  location: string | null;
  sampler_id: number | null;  // FK -> samplers.id
  start_time: string | null;
  end_time: string | null;
  status: string | null;
  sample_count: number | null;
  difficulty_level: number | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type SamplingTasksInsert = Omit<SamplingTasksRow, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type SamplingTasksUpdate = Partial<SamplingTasksInsert>;

export interface WorkHoursS6A7Bcadf8Row {
  id: number;
  corp_id: string | null;
  app_id: string | null;
  emp_id: string | null;
  sampler_id: number | null;  // FK -> samplers.id
  work_date: string;
  regular_hours: number | null;
  overtime_hours: number | null;
  weekend_hours: number | null;
  holiday_hours: number | null;
  total_hours: number | null;
  is_approved: boolean | null;
  approved_by: string | null;
  approved_at: string | null;
  is_deleted: string | null;
  created_at: string | null;
  updated_at: string | null;
}
export type WorkHoursS6A7Bcadf8Insert = Omit<WorkHoursS6A7Bcadf8Row, 'id' | 'corp_id' | 'emp_id' | 'is_deleted' | 'created_at' | 'updated_at'>;
export type WorkHoursS6A7Bcadf8Update = Partial<WorkHoursS6A7Bcadf8Insert>;
